# ---------- BUILD STAGE ----------
FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json ./
COPY apps ./apps
COPY libs ./libs

RUN pnpm install --frozen-lockfile

RUN pnpm nx build api

# ---------- RUNTIME STAGE ----------
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/api ./dist
COPY package.json pnpm-lock.yaml ./

RUN corepack enable && pnpm install --prod --frozen-lockfile

EXPOSE 4000

CMD ["node", "dist/main.js"]