name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm install -g pnpm && pnpm install

      - name: Build NX apps
        run: pnpm nx build api && pnpm nx build shell

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push backend
        run: |
          docker build -f Dockerfile.api -t cyrumao117/attendance-api:latest .
          docker push cyrumao117/attendance-api:latest

      - name: Build & push frontend
        run: |
          docker build -f Dockerfile.shell -t cyrumao117/attendance-web:latest .
          docker push cyrumao117/attendance-web:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull cyrumao117/attendance-api:latest
            docker pull cyrumao117/attendance-web:latest
            docker compose down
            docker compose up -d
